package tray

import _ "embed"

//go:generate go run icongen.go

// The menu bar icons are generated by icongen.go and committed, rather than
// computed at start. See THIRD_PARTY_NOTICES.md for the source artwork.
var (
	//go:embed icons/menubar-active.png
	activeIcon []byte
	//go:embed icons/menubar-inactive.png
	inactiveIcon []byte
)

func iconPNG(active bool) []byte {
	if active {
		return activeIcon
	}
	return inactiveIcon
}
